<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="../BetaCensor.shared.props" />
  <ItemGroup>
    <ProjectReference Include="..\BetaCensor.Core\BetaCensor.Core.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>true</IsPackable>
    <IsPublishable>false</IsPublishable>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.Extensions.FileProviders.Embedded" Version="10.0.12" />
    <PackageReference Include="LiteDB" Version="5.0.21" />
  </ItemGroup>

</Project>
