<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="../BetaCensor.shared.props" />
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>true</IsPackable>
    <IsPublishable>false</IsPublishable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Flurl" Version="3.0.7" />
    <PackageReference Include="MediatR" Version="12.5.0" />
    <PackageReference Include="Microsoft.ML.OnnxRuntime" Version="1.30.0" />
    <PackageReference Include="ModulEngine" Version="0.0.0-preview.0.5" />
    <PackageReference Include="Microsoft.Extensions.FileProviders.Abstractions" Version="10.0.12" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../../censor-core/src/CensorCore/CensorCore.csproj" />
  </ItemGroup>

</Project>
